services:
  comfy3d:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: comfy3d-dev
    shm_size: 16gb
    ports:
      - "8188:8188"
    volumes:
      - ./output:/app/comfy/output:cached
      - ./workflows:/app/comfy/user/default/workflows:cached
      - ./input:/app/comfy/input:cached
      - ./models:/app/comfy/models
      - comfyui-manager:/app/comfy/user/default/ComfyUI-Manager
      - comfyui-u2net:/root/.u2net
      - .:/workspace
    gpus: all


volumes:
  comfyui-nodes:
  comfyui-models:
  comfyui-manager:
  comfyui-u2net:

