name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # ⏱️ 2-hour timeout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch support, optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from Dockerfile
        id: extract-version
        run: |
          VERSION=$(grep -oP '(?<=ENV VERSION=)[^ ]+' Docker/Dockerfile)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Docker/Dockerfile
          push: true 
          tags: |
            michaelgold/comfy3d:latest
            michaelgold/comfy3d:${{ env.VERSION }}
          sbom: false
          provenance: false
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain

      - name: Print Docker image digest
        run: echo "Image digest: ${{ steps.docker_build.outputs.digest }}"
